#Placeholder, most of these should probably be const
abstract type GObject end
abstract type GObjectClass end
abstract type G_DEPRECATED end
abstract type GType end
abstract type gpointer end
abstract type gboolean end
abstract type GError end
abstract type gint64 end
abstract type guint64 end
abstract type gint8 end
abstract type guint8 end
abstract type gint16 end
abstract type guint16 end
abstract type gint32 end
abstract type guint32 end
abstract type gfloat end
abstract type gdouble end
abstract type gchar end
abstract type gint end
abstract type guint end
abstract type GList end
abstract type gsize end
abstract type GBytes end
abstract type GOutputStream end
abstract type GQuark end
abstract type GInputStream end
